'$schema' = "https://schema.tauri.app/config/2"
productName = "powerflow"
version = "0.1.0"
identifier = "com.powerflow.app"

[build]
beforeDevCommand = "pnpm dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "pnpm build"
frontendDist = "../dist"

[app]
macOSPrivateApi = true

[[app.windows]]
title = ""
width = 1000
height = 600
titleBarStyle = "Overlay"

[[app.windows]]
label = "popover"
url = "popover.html"
width = 398
height = 224
titleBarStyle = "Transparent"
hiddenTitle = true
alwaysOnTop = true
decorations = false
resizable = false
visible = false
transparent = true
skipTaskbar = true
focus = false


[[app.windows]]
label = "settings"
url = "settings.html"
titleBarStyle = "Overlay"
title = "Settings"
width = 700
height = 800
visible = false

[app.security]

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
