unstable_features = true
use_field_init_shorthand = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
overflow_delimited_expr = true